title: API Connect - API Marketplace
email: test@atm.ibm.com
description: IBM API Connect - API Marketplace
keywords: IBM, docker, container, devops, applications, development, iteration, microservices, cloud, ICP, services, rapid, integrated
baseurl: "/atm/api-marketplace"
repository: github.com:ibm-apiconnect/api-marketplace

# Build settings
markdown: kramdown
theme: minima
exclude: [node_modules]
collections:
  categories:
    output: true
